table dim_sede
	lineageTag: 4c30711a-bef2-4396-a51b-4ceb4ba125b8

	column id_sede
		dataType: int64
		formatString: 0
		lineageTag: 9bedf23c-b8be-4e7e-a75f-0cd6afbb59d6
		summarizeBy: none
		sourceColumn: id_sede

		annotation SummarizationSetBy = Automatic

	column nombre_sede
		dataType: string
		lineageTag: d34a3647-c606-487c-83b3-cdc725808a24
		summarizeBy: none
		sourceColumn: nombre_sede

		annotation SummarizationSetBy = Automatic

	column ubicacion_sede
		dataType: string
		lineageTag: 4220b64d-29c2-411c-96a2-75f065212102
		summarizeBy: none
		sourceColumn: ubicacion_sede

		annotation SummarizationSetBy = Automatic

	partition dim_sede = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\USUARIO\Desktop\UNI\BI\VentasVehiculos.xlsx"), null, true),
				    dim_sede_Table = Source{[Item="dim_sede",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dim_sede_Table,{{"id_sede", Int64.Type}, {"nombre_sede", type text}, {"ubicacion_sede", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

